name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # REPOSITORY: <username/username> # optional, By default, it will automatically use the repository which is executing the workflow.
          SHOW_TITLE: true
          TIME_RANGE: last_30_days
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: False
          SHOW_UPDATED_DATE: True
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_LANGUAGE: "True"
